### ISSUE TITLE
EADDRINUSE :::8888 but server does run.

### ISSUE THREAD

**Issue by Rickgrendel** [webpack-contrib/webpack-bundle-analyzer#479]
#### Issue description
When I include this plugin in my webpack configuration I get the error `Error: listen EADDRINUSE: address already in use 127.0.0.1:8888`. The strange thing is that my browser opens the bundle analyzer page which runs just fine on the aformentioned port. 

#### Technical info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 8.80 GB / 15.93 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    webpack: ^5.58.1 => 5.58.1
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0
    webpack-cli: ^4.9.0 => 4.9.0
    webpack-dev-server: ^4.3.1 => 4.3.1
```
#### Debug info
I use this as a webpack plugin with the following configuration:
 ```
new BundleAnalyzerPlugin({
          analyzerMode: 'server',
          logLevel: 'info'
}) 
```       

While using the plugin I didn't utilize any other plugin's.

The full error:

```
Error: listen EADDRINUSE: address already in use 127.0.0.1:8888
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at doListen (net.js:1516:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) 
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) 
{
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8888
}
```

**Comment by Rickgrendel** [comment]
@th0r https://github.com/Rickgrendel/eaddrinuse
